config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users' }
  resources :blog_posts
  root 'blog_posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
  mount_uploader :video, VideoUploader

  validates :title, :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :blog_posts

  mount_uploader :avatar, AvatarUploader

  validates :name, :dob, :gender, presence: true

  # Devise parameter sanitizer
  # before_save :configure_permitted_parameters

  private

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :dob, :gender])
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:name, :dob, :gender])
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_blog_post, only: [:edit, :update, :destroy]

  def index
    @blog_posts = BlogPost.all
  end

  def show
    @blog_post = BlogPost.find(params[:id])
    # The @blog_post instance variable is already set by set_blog_post method
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = current_user.blog_posts.new(blog_post_params)
    if @blog_post.save
      redirect_to @blog_post, notice: 'Blog post was successfully created.'
    else
      render :new
    end
  end

  def edit
    # The @blog_post instance variable is already set by set_blog_post method
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post, notice: 'Blog post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.'
  end

  private

  def set_blog_post
    @blog_post = current_user.blog_posts.find(params[:id])
  end

  def blog_post_params
    params.require(:blog_post).permit(:title, :description, :image, :video)
  end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  # before_action :configure_permitted_parameters, if: :devise_controller?

  # ...

  private

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :dob, :gender, :avatar])
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:name, :dob, :gender, :avatar])
  # end

  def sign_up_params
    params.require(:user).permit(:name, :dob, :gender, :email, :password, :password_confirmation, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with(model: @blog_post, local: true) do |form| %>
  <!-- ... Existing fields ... -->
  
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  
  <div class="field">
    <%= form.label :video %>
    <%= form.file_field :video %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Edit Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
<style>
  .round-image {
    border-radius: 50%;
  }
</style>

<h1>Blog Posts</h1>

<%= link_to 'Create New Blog Post', new_blog_post_path %>

<% @blog_posts.each do |blog_post| %>
  <h2><%= link_to blog_post.title, blog_post %></h2>
  <% if blog_post.image? %>
      <%= image_tag blog_post.image.url , width: "20%"%>
    <% end %>
    <% if blog_post.video? %>
      <video width="320" height="240" controls>
        <source src="<%= blog_post.video.url %>" type="video/mp4">
      </video>
    <% end %>
    <% if blog_post.user.avatar? %>
      <p>Posted by <%= image_tag blog_post.user.avatar.url , width: "3%", class: "round-image" %> <%= blog_post.user.email %> on <%= blog_post.created_at.strftime("%B %d, %Y") %></p>
    <% else %>
      <p>Posted by <%= blog_post.user.email %> on <%= blog_post.created_at.strftime("%B %d, %Y") %></p>
    <% end %>
<% end %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @blog_post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @blog_post.description %>
</p>

<% if @blog_post.image.present? %>
  <p>
    <strong>Image:</strong>
    <%= image_tag @blog_post.image.url %>
  </p>
<% end %>

<% if @blog_post.video.present? %>
  <p>
    <strong>Video:</strong>
    <%= video_tag @blog_post.video.url %>
  </p>
<% end %>

<%= button_to 'Delete', blog_post_path(@blog_post), method: :delete, data: { confirm: 'Are you sure you want to log out?' } %> |
<%= link_to 'Edit', edit_blog_post_path(@blog_post) %> |
<%= link_to 'Back', blog_posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Your Blog App</title>
  <!-- ... Your stylesheet links and other meta tags ... -->
</head>
<body>

<%= link_to "Home", root_path %>
<% if user_signed_in? %>
  <% if current_user.avatar? %>
    <%= image_tag current_user.avatar.url , width: "3%", class: "round-image" %>
  <% end %>
  <%= current_user.name %>
  <%= button_to 'Log out', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure you want to log out?' } %>
<% else %>
  <%= link_to "Login", new_user_session_path %>
  <%= link_to "Sign Up", new_user_registration_path %>
<% end %>

<%= yield %>

</body>
</html>